replaced old process #117

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -45,6 +45,7 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
       - name: Detect package manager
         id: detect-package-manager
         run: |
@@ -223,15 +224,82 @@ jobs:
 
   # Social sharing job
   mastodon:
-    name: "📡 Share to Mastodon (WIP)"
+    name: "📡 Share to Mastodon"
     runs-on: ubuntu-latest
     needs: [build, deploy]
     if: ${{ needs.build.outputs.build_status == 'started' }}
     steps:
-      - name: Match Results
-        if: ${{ needs.build.outputs.sams_social == 'new' }}
-        run: npm run sams-new-results
+      - name: Checkout
+        uses: actions/checkout@v4
 
-      - name: Blog Posts
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npm run" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+
+      - name: Restore cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+
+      - name: Match Results
+        id: match_results
+        if: ${{ needs.build.outputs.sams_social == 'new' }}
+        env:
+          CLIENT_ID: ${{ secrets.MASTODON_CLIENT_ID }}
+          ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
+        run: |
+          npm run sams-new-results
+          cat ${{ env.GITHUB_SUMMARY_FILE }} >> $GITHUB_STEP_SUMMARY
+
+      - name: Blog Posts (WIP)
+        id: blog_posts
         if: ${{ needs.build.outputs.blog_check == 'new' }}
         run: echo "To be implemented."
+
+      - name: Commit Changes
+        if: steps.match_results.conclusion == 'success'
+        continue-on-error: true
+        run: |
+          git config user.name "GitHub Actions Bot"
+          git config user.email "<>"
+
+          if [ -z "$(git stage ${{ env.SOCIAL_CACHE_MATCHES }} --dry-run)" ]
+          then
+            echo "✅ Match Results Cache file up to date."
+            echo "✅ Match Results Cache file up to date." >> $GITHUB_STEP_SUMMARY
+          else
+            echo "🏐 Match Results Cache file modified! Pushing to repository."
+            git add ${{ env.SOCIAL_CACHE_MATCHES }}
+            git commit -m "automated deployment update"
+            git push origin --all --quiet --force
+            echo "🏐 Match Results Cache file modified and pushed to repository." >> $GITHUB_STEP_SUMMARY
+          fi
